#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : gitkraken
Version  : 7.6.0
Release  : 10
URL      : https://github.com/insilications/gitkraken-clr/archive/master.zip
Source0  : https://github.com/insilications/gitkraken-clr/archive/master.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gitkraken-bin = %{version}-%{release}
Requires: gitkraken-data = %{version}-%{release}
BuildRequires : bash
BuildRequires : buildreq-cmake
BuildRequires : ca-certs
BuildRequires : cpio-bin
BuildRequires : curl
BuildRequires : curl-bin
BuildRequires : curl-dev
BuildRequires : curl-lib
BuildRequires : findutils
BuildRequires : mlocate
BuildRequires : openssl-dev
BuildRequires : openssl-lib
BuildRequires : p11-kit
BuildRequires : pcre-dev
BuildRequires : pcre-extras
BuildRequires : rpm
BuildRequires : rpm-extras
BuildRequires : xmlstarlet
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
# Disable automatic requeriments processing
AutoReq: no
# Disable automatic provides processing
AutoProv: no

%description
No detailed description available

%package bin
Summary: bin components for the gitkraken package.
Group: Binaries
Requires: gitkraken-data = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no
# Disable automatic provides processing
AutoProv: no

%description bin
bin components for the gitkraken package.


%package data
Summary: data components for the gitkraken package.
Group: Data
# Disable automatic requeriments processing
AutoReq: no
# Disable automatic provides processing
AutoProv: no

%description data
data components for the gitkraken package.


%package doc
Summary: doc components for the gitkraken package.
Group: Documentation
# Disable automatic requeriments processing
AutoReq: no
# Disable automatic provides processing
AutoProv: no

%description doc
doc components for the gitkraken package.


%prep
%setup -q -n gitkraken-clr-master
cd %{_builddir}/gitkraken-clr-master

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1620878194
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1620878194
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gitkraken
/usr/share/gitkraken/resources/bin/gitkraken.sh

%files data
%defattr(-,root,root,-)
/usr/share/applications/gitkraken.desktop
/usr/share/gitkraken/LICENSE.electron
/usr/share/gitkraken/LICENSES.chromium.html
/usr/share/gitkraken/chrome-sandbox
/usr/share/gitkraken/chrome_100_percent.pak
/usr/share/gitkraken/chrome_200_percent.pak
/usr/share/gitkraken/gitkraken
/usr/share/gitkraken/gitkraken-url-handler.desktop
/usr/share/gitkraken/icudtl.dat
/usr/share/gitkraken/libEGL.so
/usr/share/gitkraken/libGLESv2.so
/usr/share/gitkraken/libffmpeg.so
/usr/share/gitkraken/libvk_swiftshader.so
/usr/share/gitkraken/libvulkan.so
/usr/share/gitkraken/locales/am.pak
/usr/share/gitkraken/locales/ar.pak
/usr/share/gitkraken/locales/bg.pak
/usr/share/gitkraken/locales/bn.pak
/usr/share/gitkraken/locales/ca.pak
/usr/share/gitkraken/locales/cs.pak
/usr/share/gitkraken/locales/da.pak
/usr/share/gitkraken/locales/de.pak
/usr/share/gitkraken/locales/el.pak
/usr/share/gitkraken/locales/en-GB.pak
/usr/share/gitkraken/locales/en-US.pak
/usr/share/gitkraken/locales/es-419.pak
/usr/share/gitkraken/locales/es.pak
/usr/share/gitkraken/locales/et.pak
/usr/share/gitkraken/locales/fa.pak
/usr/share/gitkraken/locales/fi.pak
/usr/share/gitkraken/locales/fil.pak
/usr/share/gitkraken/locales/fr.pak
/usr/share/gitkraken/locales/gu.pak
/usr/share/gitkraken/locales/he.pak
/usr/share/gitkraken/locales/hi.pak
/usr/share/gitkraken/locales/hr.pak
/usr/share/gitkraken/locales/hu.pak
/usr/share/gitkraken/locales/id.pak
/usr/share/gitkraken/locales/it.pak
/usr/share/gitkraken/locales/ja.pak
/usr/share/gitkraken/locales/kn.pak
/usr/share/gitkraken/locales/ko.pak
/usr/share/gitkraken/locales/lt.pak
/usr/share/gitkraken/locales/lv.pak
/usr/share/gitkraken/locales/ml.pak
/usr/share/gitkraken/locales/mr.pak
/usr/share/gitkraken/locales/ms.pak
/usr/share/gitkraken/locales/nb.pak
/usr/share/gitkraken/locales/nl.pak
/usr/share/gitkraken/locales/pl.pak
/usr/share/gitkraken/locales/pt-BR.pak
/usr/share/gitkraken/locales/pt-PT.pak
/usr/share/gitkraken/locales/ro.pak
/usr/share/gitkraken/locales/ru.pak
/usr/share/gitkraken/locales/sk.pak
/usr/share/gitkraken/locales/sl.pak
/usr/share/gitkraken/locales/sr.pak
/usr/share/gitkraken/locales/sv.pak
/usr/share/gitkraken/locales/sw.pak
/usr/share/gitkraken/locales/ta.pak
/usr/share/gitkraken/locales/te.pak
/usr/share/gitkraken/locales/th.pak
/usr/share/gitkraken/locales/tr.pak
/usr/share/gitkraken/locales/uk.pak
/usr/share/gitkraken/locales/vi.pak
/usr/share/gitkraken/locales/zh-CN.pak
/usr/share/gitkraken/locales/zh-TW.pak
/usr/share/gitkraken/resources.pak
/usr/share/gitkraken/resources/app.asar
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/keytar/build/Release/keytar.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/acquireOpenSSL.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/configureLibssh2.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-centos-7.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-debian-8.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-fedora-28.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-ubuntu-18.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/pathwatcher/build/Release/pathwatcher.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/find-git-repositories/build/Release/findGitRepos.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/font-scanner/build/Release/fontmanager.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/nodegit-large-file-storage/askpass.sh
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/nodegit-large-file-storage/build/src/utils/GitAskPass.js
/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/nsfw/build/Release/nsfw.node
/usr/share/gitkraken/resources/app.asar.unpacked/src/THIRD-PARTY-LICENSES.txt
/usr/share/gitkraken/resources/app.asar.unpacked/src/js/redux/domain/AskPass/AskPass.sh
/usr/share/gitkraken/resources/app.asar.unpacked/src/js/redux/domain/AskPass/AskPassClient.js
/usr/share/gitkraken/resources/app.asar.unpacked/src/strings.json
/usr/share/gitkraken/resources/default_app.asar
/usr/share/gitkraken/snapshot_blob.bin
/usr/share/gitkraken/swiftshader/libEGL.so
/usr/share/gitkraken/swiftshader/libGLESv2.so
/usr/share/gitkraken/v8_context_snapshot.bin
/usr/share/gitkraken/version
/usr/share/gitkraken/vk_swiftshader_icd.json
/usr/share/pixmaps/gitkraken.png

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/gitkraken/*
